[workspace]
members = ["crates/*"]

[workspace.package]
repository = "https://github.com/seanmonstar/reqwest"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"
